name: Release (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (unused - auto-detected from package.json)"
        required: false
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - uses: actions/checkout@master
      - name: Build Stage
        run: |
          npm install
          npm run plugin-zip

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Modula Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: modula-best-grid-gallery
          VERSION: ${{ steps.package-version.outputs.current-version }}
